/*
-- Query: SELECT * FROM cuenta
LIMIT 0, 1000

-- Date: 2021-11-14 20:28
*/
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1000,'ACTIVO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1100,'ACTIVO CORRIENTE','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1101,'EFECTIVO Y EQUIVALENTES DE EFECTIVO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1102,'CUENTAS Y DOCUMENTOS POR COBRAR','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1103,'CUENTAS POR COBRAR ARRENDAMIENTO FINANCIERO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1104,'INVENTARIOS','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1105,'PEDIDOS EN TRANSITO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1106,'RESERVA PARA OBSOLESCENCIA DE INVENTARIOS','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1107,'INVERSIONES TEMPORALES','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1108,'PARTES RELACIONADAS','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1109,'GASTOS PAGADOS POR ANTICIPADO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1110,'IVA - CRÉDITO FISCAL','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1111,'PAGO A CUENTA - IMPUESTO SOBRE RENTA','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1112,'DIVIDENDOS POR COBRAR','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1113,'ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1200,'ACTIVO NO CORRIENTE','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1201,'PROPIEDAD PLANTA Y EQUIPO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1202,'DEPRECIACIÓN ACUM. DE PROPIEDAD PLANTA Y EQUIPO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1203,'DETERIORO ACUM. DE PROPIEDAD PLANTA Y EQUIPO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1204,'REVALUACIÓN DE PROPIEDAD PLANTA Y EQUIPO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1205,'DEPRECIACIÓN DE REVALUOS DE PROPIEDAD PLANTA Y EQUIPO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1206,'PROPIEDAD PLANTA Y EQUIPO EN ARRENDAMIENTO FINANCIERO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1207,'DEPRECIACIÓN ACUMULADA DE PROPIEDAD PLANTA Y EQ. EN ARRENDAMIENTO FINANCIERO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1208,'CONSTRUCCIÓN EN PROCESO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1209,'INVERSIONES PERMANENTES','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1210,'IMPUESTO SOBRE LA RENTA DIFERIDO CUENTA DE ACTIVO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1211,'ACTIVOS INTANGIBLES','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1212,'AMORTIZACIÓN DE INTANGIBLES','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1213,'DETERIORO ACUMULADO DE ACTIVOS INTANGIBLES','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1214,'CUENTAS Y DOCUMENTOS POR COBRAR LARGO PLAZO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1215,'PRÉSTAMOS A ACCIONISTAS LARGO PLAZO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1216,'OTRAS CUENTAS POR COBRAR LARGO PLAZO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1217,'DEPOSITOS EN GARANTIA LARGO PLAZO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1218,'CUENTAS POR COBRAR ARRENDAMIENTO FINANCIERO LARGO PLAZO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (1219,'PARTES RELACIONADAS LARGO PLAZO','Activos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2000,'PASIVO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2100,'PASIVO CORRIENTE','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2101,'PRÉSTAMOS Y SOBREGIROS BANCARIOS','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2102,'CUENTAS Y DOCUMENTOS POR PAGAR','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2103,'PORCIÓN CIRCULANTE DE ARRENDAMIENTO FINANCIERO LARGO PLAZO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2104,'PROVISIONES Y RETENCIONES','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2105,'BENEFICIOS A EMPLEADOS POR PAGA','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2106,'ACREEDORES VARIOS','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2107,'DIVIDENDOS POR PAGAR','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2108,'IVA - DEBITO FISCAL','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2109,'IMPUESTOS POR PAGA','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2110,'INTERESES POR PAGAR','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2111,'PARTES RELACIONADAS CORTO PLAZO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2200,'PASIVO NO CORRIENTE','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2201,'PRÉSTAMOS BANCARIOS A LARGO PLAZO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2202,'DOCUMENTOS POR PAGAR - LARGO PLAZO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2203,'OBLIGACIONES POR ARRENDAMIENTO FINANCIERO LARGO PLAZO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2204,'IMPUESTO SOBRE LA RENTA DIFERIDO CUENTA PASIVO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2205,'BENEFICIOS A EMPLEADOS POR PAGAR LARGO PLAZO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (2206,'PARTES RELACIONADAS LARGO PLAZO','Pasivos');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (3000,'PATRIMONIO','Patrimonio');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (3100,'CAPITAL CONTABLE','Patrimonio');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (3101,'CAPITAL SOCIAL','Patrimonio');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (3102,'SUPERAVIT POR REVALUACION DE PROPIEDAD PLANTA Y EQUIPO NO REALIZADA','Patrimonio');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (3103,'RESERVA LEGAL','Patrimonio');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (3104,'UTILIDADES POR DISTRIBUIR','Patrimonio');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (3105,'SUPERAVIT POR REVALUACION DE PROPIEDAD PLANTA Y EQUIPO REALIZADO','Patrimonio');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (3106,'DEFICIT ACUMULADO','Patrimonio');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (4000,'CUENTAS DE RESULTADO DEUDORAS','Cuentas de resultado deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (4100,'COSTOS Y GASTOS DE OPERACIÓN','Cuentas de resultado deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (4101,'COSTO DE VENTA','Cuentas de resultado deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (4102,'GASTOS DE VENTA','Cuentas de resultado deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (4103,'GASTOS DE ADMINISTRACIÓN','Cuentas de resultado deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (4104,'IMPUESTO SOBRE LA RENTA','Cuentas de resultado deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (4105,'GASTOS FINANCIEROS','Cuentas de resultado deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (4106,'PÉRDIDA POR VENTA DE ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA','Cuentas de resultado deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (5000,'CUENTAS DE RESULTADO ACREEDORAS','Cuentas de resultado acreedoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (5100,'INGRESOS DE OPERACIÓN','Cuentas de resultado acreedoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (5101,'INGRESOS POR VENTAS','Cuentas de resultado acreedoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (5102,'PRODUCTOS FINANCIEROS','Cuentas de resultado acreedoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (5103,'PÉRDIDA POR VENTA DE ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA','Cuentas de resultado acreedoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (6000,'CUENTA LIQUIDADORA O DE CIERRE','Cuentas liquidadora o de cierre');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (6100,'CUENTA LIQUIDADORA O DE CIERRE','Cuentas liquidadora o de cierre');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (6101,'PÉRDIDAS Y GANANCIAS','Cuentas liquidadora o de cierre');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (7000,'CUENTAS DE MEMORANDUM DEUDORAS','Cuentas de memorandum deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (7100,'CUENTAS DE ORDEN DEUDORAS','Cuentas de memorandum deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (7101,'CUENTAS DE ORDEN DEUDORAS','Cuentas de memorandum deudoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (8000,'CUENTAS DE MEMORANDUM ACREEDORAS','Cuentas de memorandum acreedoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (8100,'CUENTAS DE ORDEN ACREEDORAS','Cuentas de memorandum acreedoras');
INSERT INTO `` (`catalogoId`,`nombre`,`tipo`) VALUES (8101,'CUENTAS DE ORDEN ACREEDORAS','Cuentas de memorandum acreedoras');
